[package]
name = "snof"
description = "Unique ID generator"
version = "0.1.0"
edition = "2024"
authors = ["mellowcoffee"]
repository = "https://github.com/mellowcoffee/snof"
homepage = "https://github.com/mellowcoffee/snof"
readme = "readme.md"
license-file = "license"

[dependencies]
